### ISSUE TITLE
Augmented heads can't have self-surgery done on them

### ISSUE THREAD

**Issue by cuckooman** [The-Merchants-Guild/Merchant-Station-13#224]
i'm not good at writing issues don't reee at me over this
## Round ID:
idfk
## Testmerges:
i don't think any testmerges factor into this

## Reproduction:
1. Get someone to perform the "Augmentation" procedure on your head.
2. Attempt to perform a surgical procedure on your head (make sure it's uncovered)
3. Observe that it doesn't work (that's like the main reason to get augs)

**Comment by TheChosenEvilOne** [comment]
this is caused by the self-surgery changes in #88

**Comment by Bomk16** [comment]
> this is caused by the self-surgery changes in #88

"Blah blah blah" shut UP bro you're weird!!!!

On another note I believe we should revert this change as the server is generally more lowpop so bring able to solo surgery yourself could be crucial if you're trying to do certain stuff since the person who augged you won't always be around to do more surgery on your head (for instance installing a cyberlink)

**Comment by Bomk16** [comment]
``

> > this is caused by the self-surgery changes in #88
> 
> "Blah blah blah" shut UP bro you're weird!!!!
> 
> On another note I believe we should revert this change as the server is generally more lowpop so bring able to solo surgery yourself could be crucial if you're trying to do certain stuff since the person who augged you won't always be around to do more surgery on your head (for instance installing a cyberlink)

Also augmented was meant so you can do self surgery on ALL body parts since you couldn't do self surgery as a non augged originally and this might have been an oversight
